### ISSUE TITLE
Use `Logger` to Log Info + Errors!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gogs#13]
At present I've got a few `IO.inspect` statements peppered in the code (_all commented out_)
We can/should do better for debugging our apps in our staging (and even `prod`) environments!

# Todo

+ [x] Add `Logger` statements in the code in strategic places e.g. errors and info.
+ [x] Borrow heavily from: 
  + [x] https://github.com/dwyl/envar/blob/main/lib/envar.ex#L10 
  + [x] https://github.com/dwyl/auth_plug/blob/main/lib/auth_plug.ex#L19

**Comment by nelsonic** [comment]
E.g: 
https://github.com/dwyl/gogs/blob/578e95666b1c3fbed2316b2537efba3971f941d2/lib/gogs.ex#L110
