### ISSUE TITLE
Gogs.push/1 Should Push the Current Branch to Gogs Server

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gogs#16]
We've already got _most_ of the functions we need documented, tested and written: https://hexdocs.pm/gogs 🚀 
This is the penultimate piece in the puzzle. And without it all the other functions are just "Work in Progress" ...

# Todo

+ [x] Push current branch e.g. `master`, `main`, `draft` etc. to the remote Gogs Server
+ [x] Mock the function for GitHub/Test so that (a) it can run on CI and (b) it runs _faster_ during tests.
+ [x] Write tests.
+ [x] Document it!
+ [x] Release new version of the package to Hex.pm

**Comment by nelsonic** [comment]
Implementation:
https://github.com/dwyl/gogs/blob/cd3ea2e61ae6d6ce21ef818035b5324309da2fc6/lib/gogs.ex#L163-L176

Mock:
https://github.com/dwyl/gogs/blob/cd3ea2e61ae6d6ce21ef818035b5324309da2fc6/lib/git_mock.ex#L30-L42

**Comment by nelsonic** [comment]
On Hex.pm: https://hexdocs.pm/gogs/0.4.0/Gogs.html#push/1
