### ISSUE TITLE
Get Raw Contents of File from Git Repo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gogs#21]
While building the demo: dwyl/gitea-demo#3
I've spotted a _glaring_ omission: We don't currently have a way to _read_ the contents of a file.
We're doing this with _custom_ code in the App we're building.
But it's an _obvious_ use case so should be included in the library.
Thankfully it won't be too much work to create it because it's just _local_ filesystem access.

# Todo

+ [x] Create `remote_read_raw/4`  - with `org_name`, `repo_name` and `file_name` as arguments
+ [x] `local_file_read/3` same args. self-explanatory
+ [x] Should return the raw contents of the file for display.
+ [x] Test
+ [x] Docs
+ [x] Publish!

**Comment by nelsonic** [comment]
Gonna pick this up tomorrow morning when I'm back on Mac work. 🧑‍💻 
Just setting up my _brain_ to do the work. 📝 
See: "_Organize Tomorrow Today_" by Jason Selk & Tom Bartow: https://youtu.be/yRLEr69qPd4 💭

**Comment by nelsonic** [comment]
This looks like the API endpoint we need for reading the remote file: 
https://github.com/gogs/docs-api/blob/master/Repositories/Contents.md#get-contents

Doesn't _appear_ to allow specifying a branch tho ... 💭

**Comment by nelsonic** [comment]
It's technically _working_ ... but the response is this:

```elixir
{:ok,
 %{
   _links: %{
     git: "https://gogs-server.fly.dev/api/v1/repos/myorg/public-repo/git/blobs/506c3895bd3bb2f3715079a56ed898847b89e4aa",
     html: "https://gogs-server.fly.dev/myorg/public-repo/src/master/README.md",
     self: "https://gogs-server.fly.dev/api/v1/repos/myorg/public-repo/contents/README.md"
   },
   content: "IyBwdWJsaWMtcmVwbwoKcGxlYXNlIGRvbid0IHVwZGF0ZSB0aGlzLiB0aGUgdGVzdHMgcmVhZCBpdC4=",
   download_url: "https://gogs-server.fly.dev/myorg/public-repo/raw/master/README.md",
   encoding: "base64",
   git_url: "https://gogs-server.fly.dev/api/v1/repos/myorg/public-repo/git/blobs/506c3895bd3bb2f3715079a56ed898847b89e4aa",
   html_url: "https://gogs-server.fly.dev/myorg/public-repo/src/master/README.md",
   name: "README.md",
   path: "README.md",
   sha: "506c3895bd3bb2f3715079a56ed898847b89e4aa",
   size: 59,
   type: "file",
   url: "https://gogs-server.fly.dev/api/v1/repos/myorg/public-repo/contents/README.md"
 }}
```
Which is actually _useless_ for our purposes.
Need get the _raw_ content!

**Comment by nelsonic** [comment]
Shipped the _first_ part of this: https://hexdocs.pm/gogs/Gogs.html#remote_read_raw/4

**Comment by nelsonic** [comment]
Second part shipped: https://hexdocs.pm/gogs/Gogs.html#local_file_read/3
Created usage example in the `README.md`: https://github.com/dwyl/gogs#usage
And step-by-step example in: https://github.com/dwyl/gogs-demo#4-create-function-to-interact-with-gogs-repo

Closing as consider this #done ✅ 
P.s. the last build that referenced this issue failed because `mock: false`
As soon as I restored it to `mock: true` it passed CI: https://github.com/dwyl/gogs/actions/runs/2302074546

**Comment by nelsonic** [comment]
@SimonLab your feedback is very much encouraged on this. If you can spot an improvement, please shout! 🙏
