### ISSUE TITLE
Create Repo on Fly.io Gogs instance

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gogs#9]
The first step (after creating an `Org` #8 ...) in using Gogs as a Backup for GitHub is to create a Repository!
Reading the API: https://github.com/gogs/docs-api/tree/master/Repositories#create

It appears this should be straightforward:

```sh
POST /org/:org/repos
```

# Todo

+ [x] Create an interface to this endpoint that easily allows us to create a Repository e.g. `Gogs.remote_repo_create/3`
+ [x] Expose a **`Test Double`** that returns the desired payload when invoked during testing.
  + [x] e.g: https://github.com/dwyl/elixir-auth-google/blob/main/lib/httpoison_mock.ex

**Comment by nelsonic** [comment]
Creating a new repo via `cURL` (REST API) is working on my localhost!

```sh
curl -X POST -H "Content-Type: application/json" -d '{"name": "created-by-curl", "description": "This is your first repository",  "private": false}'  'https://gogs-server.fly.dev/api/v1/org/myorg/repos?token=yourtoken'
```

![image](https://user-images.githubusercontent.com/194400/166169507-c8b4d570-b699-463c-bfbe-e7f474095ea3.png)

response:

```json
{
	"id": 5,
	"owner": {
		"id": 2,
		"username": "myorg",
		"login": "myorg",
		"full_name": "",
		"email": "",
		"avatar_url": "https://gogs-server.fly.dev/avatars/2"
	},
	"name": "created-by-curl",
	"full_name": "myorg/created-by-curl",
	"description": "This is your first repository",
	"private": false,
	"fork": false,
	"parent": null,
	"empty": false,
	"mirror": false,
	"size": 0,
	"html_url": "https://gogs-server.fly.dev/myorg/created-by-curl",
	"ssh_url": "ssh://git@gogs-server.fly.dev:10022/myorg/created-by-curl.git",
	"clone_url": "https://gogs-server.fly.dev/myorg/created-by-curl.git",
	"website": "",
	"stars_count": 0,
	"forks_count": 0,
	"watchers_count": 0,
	"open_issues_count": 0,
	"default_branch": "",
	"created_at": "0001-01-01T00:00:00Z",
	"updated_at": "0001-01-01T00:00:00Z",
	"permissions": {
		"admin": true,
		"push": true,
		"pull": true
	}
}
```

This means it will work via `HTTPoison` tomorrow morning. 😴 
And once that is working, we're off to the races!! 🐎

**Comment by nelsonic** [comment]
I've setup all the code to make REST API Requests from Elixir using `HTTPoison` (_piggy-backing on previous work done in https://github.com/dwyl/elixir-auth-google/blame/9c2b4b96f6829719faa767f1db57c9ba09131380/lib/elixir_auth_google.ex#L89 ...

But getting a **`415`** error: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415

```elixir
%HTTPoison.Response{
  body: "[{\"classification\":\"ContentTypeError\",\"message\":\"Unsupported Content-Type\"}]",
  headers: [
    {"content-type", "application/json; charset=utf-8"},
    {"set-cookie", "lang=en-US; Path=/; Max-Age=2147483647"},
    {"set-cookie", "i_like_gogs=ba89f24ea6c11533; Path=/; HttpOnly"},
    {"set-cookie",
     "_csrf=xOXKySlsS26hdUvN1acemGQ5aOQ6MTY1MTQ4NzkyMzg5MTUwMDYzNA; Path=/; Domain=gogs-server.fly.dev; Expires=Tue, 03 May 2022 10:38:43 GMT; HttpOnly; Secure"},
    {"x-content-type-options", "nosniff"},
    {"x-frame-options", "DENY"},
    {"date", "Mon, 02 May 2022 10:38:43 GMT"},
    {"content-length", "76"},
    {"server", "Fly/f2e6d63f (2022-04-27)"},
    {"via", "1.1 fly.io"},
    {"fly-request-id", "01G225KT6TNN28MXJX3K40V18P-lhr"}
  ],
  request: %HTTPoison.Request{
    body: "{\"name\":\"test-repo6\",\"private\":false}",
    headers: [
      {"Authorization", "token supersecret"}
    ],
    method: :post,
    options: [],
    params: %{},
    url: "https://gogs-server.fly.dev/api/v1/org/myorg/repos"
  },
  request_url: "https://gogs-server.fly.dev/api/v1/org/myorg/repos",
  status_code: 415
}
{:ok,
 [
   %{
     "classification" => "ContentTypeError",
     "message" => "Unsupported Content-Type"
   }
 ]}
```

Did a bit of goggling ... 🔍 
Found: https://www.npmjs.com/package/gogs-client
Which specifies the `Content-Type` header as:

```js
      headers: {'Content-Type': 'application/json'}
```
https://github.com/unfoldingWord-dev/node-gogs-client/blob/6b16291e1a1e05882cc2d0628128a6ab6d3047a5/lib/request.js#L44

And now our **`REST API`** Request works:

```sh
{:ok,
 %{
   clone_url: "https://gogs-server.fly.dev/myorg/test-repo7.git",
   created_at: "0001-01-01T00:00:00Z",
   default_branch: "",
   description: "",
   empty: false,
   fork: false,
   forks_count: 0,
   full_name: "myorg/test-repo7",
   html_url: "https://gogs-server.fly.dev/myorg/test-repo7",
   id: 6,
   mirror: false,
   name: "test-repo7",
   open_issues_count: 0,
   owner: %{
     avatar_url: "https://gogs-server.fly.dev/avatars/2",
     email: "",
     full_name: "",
     id: 2,
     login: "myorg",
     username: "myorg"
   },
   parent: nil,
   permissions: %{admin: true, pull: true, push: true},
   private: false,
   size: 0,
   ssh_url: "ssh://git@gogs-server.fly.dev:10022/myorg/test-repo7.git",
   stars_count: 0,
   updated_at: "0001-01-01T00:00:00Z",
   watchers_count: 0,
   website: ""
 }}
```

https://gogs-server.fly.dev/myorg/test-repo7
![image](https://user-images.githubusercontent.com/194400/166222254-6887e26d-82e5-4034-ba11-ff7cbf3a745f.png)

# `#milestone`

**Comment by nelsonic** [comment]
The test & TestDouble code is 4x the code for the actual implementation. 🙄

**Comment by nelsonic** [comment]
Ref:

https://github.com/dwyl/gogs/blob/ec08eb42773333890cebc0baedf1680f7ced4a0c/lib/gogs.ex#L56-L74
